kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: demo-iam404
  name: datadir-minikube
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile

provisioner: k8s.io/minikube-hostpath
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: demo-iam404
  name: etcd
spec:
  serviceName: etcd
  #                                                         #
  # Please do not change the replica count.                 #
  # This file is not created to run etcd in cluster mode.   #
  #                                                         #
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
        component : datastore

    spec:
      containers:
      - name: etcd
        imagePullPolicy: Always
        image: quay.io/coreos/etcd:v2.0.8
        resources:
          requests:
            memory: "500m"
            cpu: "0.5"

        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: server
          protocol: TCP
        command:
        - ./etcd
        - --name
        - etcd0
        - --initial-advertise-peer-urls
        - http://etcd:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd:2379,http://0.0.0.0:2379,http://127.0.0.1:2379
        - --initial-cluster
        - etcd0=http://etcd:2380
        - --initial-cluster-state
        - new

        volumeMounts:
        - name: datadir
          mountPath: /etcd_data

  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: "datadir-minikube"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: demo-iam404
  name: etcd
spec:
  type: NodePort
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd

---


